name: Tests

on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]

env:
  REF: ${{ github.event.pull_request.head.sha || github.sha }}


jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REF }}
      - name: Docker build
        run: docker build . -t scoap3/workflows:${REF}
      - name: Run tests
        run: docker run --rm scoap3/workflows:${REF} pytest workflows_tests
