name: Tests

on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REF }}

      - name: Docker build
        run: docker build . -t scoap3/workflows:${{ github.sha }}

      - name: Run tests
        run: docker run --rm scoap3/workflows:${{ github.sha }} pytest workflows_tests

      - name: Set up QEMU
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: scoap3/workflows:latest,scoap3/workflows:${{ github.sha }}
